// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0-devel
// 	protoc        (unknown)
// source: protobuf/clientModelsKV.proto

package protobuf

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ClientPutStateKVRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// the key of KV
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// the value of KV
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *ClientPutStateKVRequest) Reset() {
	*x = ClientPutStateKVRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_clientModelsKV_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientPutStateKVRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientPutStateKVRequest) ProtoMessage() {}

func (x *ClientPutStateKVRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_clientModelsKV_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientPutStateKVRequest.ProtoReflect.Descriptor instead.
func (*ClientPutStateKVRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_clientModelsKV_proto_rawDescGZIP(), []int{0}
}

func (x *ClientPutStateKVRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ClientPutStateKVRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type ClientPutStateKVResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// boolean indicator, whether the LogEntry is created and committed
	Committed bool `protobuf:"varint,1,opt,name=committed,proto3" json:"committed,omitempty"`
	// if the requested peer is not the current leader, return the leader ip:port
	CurrentLeader string `protobuf:"bytes,2,opt,name=currentLeader,proto3" json:"currentLeader,omitempty"`
}

func (x *ClientPutStateKVResponse) Reset() {
	*x = ClientPutStateKVResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_clientModelsKV_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientPutStateKVResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientPutStateKVResponse) ProtoMessage() {}

func (x *ClientPutStateKVResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_clientModelsKV_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientPutStateKVResponse.ProtoReflect.Descriptor instead.
func (*ClientPutStateKVResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_clientModelsKV_proto_rawDescGZIP(), []int{1}
}

func (x *ClientPutStateKVResponse) GetCommitted() bool {
	if x != nil {
		return x.Committed
	}
	return false
}

func (x *ClientPutStateKVResponse) GetCurrentLeader() string {
	if x != nil {
		return x.CurrentLeader
	}
	return ""
}

type ClientDelStateKVRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// the key of KV
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *ClientDelStateKVRequest) Reset() {
	*x = ClientDelStateKVRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_clientModelsKV_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientDelStateKVRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDelStateKVRequest) ProtoMessage() {}

func (x *ClientDelStateKVRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_clientModelsKV_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDelStateKVRequest.ProtoReflect.Descriptor instead.
func (*ClientDelStateKVRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_clientModelsKV_proto_rawDescGZIP(), []int{2}
}

func (x *ClientDelStateKVRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ClientDelStateKVResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// boolean indicator, whether the LogEntry is created and committed
	Committed bool `protobuf:"varint,1,opt,name=committed,proto3" json:"committed,omitempty"`
	// if the requested peer is not the current leader, return the leader ip:port
	CurrentLeader string `protobuf:"bytes,2,opt,name=currentLeader,proto3" json:"currentLeader,omitempty"`
}

func (x *ClientDelStateKVResponse) Reset() {
	*x = ClientDelStateKVResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_clientModelsKV_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientDelStateKVResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDelStateKVResponse) ProtoMessage() {}

func (x *ClientDelStateKVResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_clientModelsKV_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDelStateKVResponse.ProtoReflect.Descriptor instead.
func (*ClientDelStateKVResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_clientModelsKV_proto_rawDescGZIP(), []int{3}
}

func (x *ClientDelStateKVResponse) GetCommitted() bool {
	if x != nil {
		return x.Committed
	}
	return false
}

func (x *ClientDelStateKVResponse) GetCurrentLeader() string {
	if x != nil {
		return x.CurrentLeader
	}
	return ""
}

type ClientGetStateKVRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// the key of KV
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *ClientGetStateKVRequest) Reset() {
	*x = ClientGetStateKVRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_clientModelsKV_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientGetStateKVRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientGetStateKVRequest) ProtoMessage() {}

func (x *ClientGetStateKVRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_clientModelsKV_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientGetStateKVRequest.ProtoReflect.Descriptor instead.
func (*ClientGetStateKVRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_clientModelsKV_proto_rawDescGZIP(), []int{4}
}

func (x *ClientGetStateKVRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ClientGetStateKVResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// boolean tag whether get state succeeded
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// the value of KV
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ClientGetStateKVResponse) Reset() {
	*x = ClientGetStateKVResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_clientModelsKV_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientGetStateKVResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientGetStateKVResponse) ProtoMessage() {}

func (x *ClientGetStateKVResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_clientModelsKV_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientGetStateKVResponse.ProtoReflect.Descriptor instead.
func (*ClientGetStateKVResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_clientModelsKV_proto_rawDescGZIP(), []int{5}
}

func (x *ClientGetStateKVResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClientGetStateKVResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_protobuf_clientModelsKV_proto protoreflect.FileDescriptor

var file_protobuf_clientModelsKV_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x4b, 0x56, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x45, 0x0a, 0x17, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x50, 0x75, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4b, 0x56, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x22, 0x5e, 0x0a, 0x18, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x75, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x4b, 0x56, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x22, 0x2b, 0x0a, 0x17, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x6c, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x4b, 0x56, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x5e, 0x0a,
	0x18, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4b,
	0x56, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x63, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x2b, 0x0a,
	0x17, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4b,
	0x56, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x4a, 0x0a, 0x18, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4b, 0x56, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x72, 0x61, 0x66, 0x74, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_clientModelsKV_proto_rawDescOnce sync.Once
	file_protobuf_clientModelsKV_proto_rawDescData = file_protobuf_clientModelsKV_proto_rawDesc
)

func file_protobuf_clientModelsKV_proto_rawDescGZIP() []byte {
	file_protobuf_clientModelsKV_proto_rawDescOnce.Do(func() {
		file_protobuf_clientModelsKV_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_clientModelsKV_proto_rawDescData)
	})
	return file_protobuf_clientModelsKV_proto_rawDescData
}

var file_protobuf_clientModelsKV_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protobuf_clientModelsKV_proto_goTypes = []interface{}{
	(*ClientPutStateKVRequest)(nil),  // 0: protobuf.ClientPutStateKVRequest
	(*ClientPutStateKVResponse)(nil), // 1: protobuf.ClientPutStateKVResponse
	(*ClientDelStateKVRequest)(nil),  // 2: protobuf.ClientDelStateKVRequest
	(*ClientDelStateKVResponse)(nil), // 3: protobuf.ClientDelStateKVResponse
	(*ClientGetStateKVRequest)(nil),  // 4: protobuf.ClientGetStateKVRequest
	(*ClientGetStateKVResponse)(nil), // 5: protobuf.ClientGetStateKVResponse
}
var file_protobuf_clientModelsKV_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_clientModelsKV_proto_init() }
func file_protobuf_clientModelsKV_proto_init() {
	if File_protobuf_clientModelsKV_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_clientModelsKV_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientPutStateKVRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_clientModelsKV_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientPutStateKVResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_clientModelsKV_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientDelStateKVRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_clientModelsKV_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientDelStateKVResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_clientModelsKV_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientGetStateKVRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_clientModelsKV_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientGetStateKVResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_clientModelsKV_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_clientModelsKV_proto_goTypes,
		DependencyIndexes: file_protobuf_clientModelsKV_proto_depIdxs,
		MessageInfos:      file_protobuf_clientModelsKV_proto_msgTypes,
	}.Build()
	File_protobuf_clientModelsKV_proto = out.File
	file_protobuf_clientModelsKV_proto_rawDesc = nil
	file_protobuf_clientModelsKV_proto_goTypes = nil
	file_protobuf_clientModelsKV_proto_depIdxs = nil
}
