# Config file for distributed lock based on raft

node:
  meta_data:
    id: 1
  network:
    self_address: 192.168.0.1:14005
    peer_address:
      - 192.168.0.2:14005
      - 192.168.0.3:14005
  config:
    # the interval for leader to push heart beat package to followers, unit:ms
    heart_beat_interval: 50
    # the timeout for every AppendEntriesRequest, unit:ms
    append_entries_timeout: 150
    # the maximum and minimum time before become a candidate, unit:ms
    min_wait_time_candidate: 150
    max_wait_time_candidate: 300
    # maximum number of log units in RecoverEntriesResponse 
    max_log_units_recover: 200
  storage:
    log_path: "$GOPATH/src/github.com/dlock_raft/var"
    entry_storage_path: "$GOPATH/src/github.com/dlock_raft/var/persistance.db"


